### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by durban** [scala-exercises/exercises-shapeless#27]
Running the first exercise on page https://www.scala-exercises.org/shapeless/extensible_records results in a strange compile error:
```
Compilation error: java.lang.NoClassDefFoundError: shapeless/syntax/RecordOps$
```

**Comment by raulraja** [comment]
@durban This should be fixed now. Thanks for reporting it. The issue was sue to the old Evaluator not being thread safe and leaving the compiler in an inconsistent state after more than one concurrent request asked the evaluator to compile some code.
